export { default as IconGear } from './Gear.vue'
export { default as IconHome } from './Home.vue'
export { default as IconInfo } from './Info.vue'
export { default as IconLight } from './Light.vue'
export { default as IconTemp } from './Temp.vue'
